openapi: 3.0.0
info:
  title: SNAP API Direct Debit
  description: Backend Integration to check status API
  version: "1.0"
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://{api-domain}

paths:
  /orders/v1.0/debit/status:
    post:
      summary: Check Direct Debit Status
      description: Get the status and details of a direct debit transaction
      operationId: checkDebitStatus
      tags:
        - Backend Integration to check status Virtual Account
      parameters:
        - in: header
          name: X-TIMESTAMP
          required: true
          schema:
            type: string
            format: date-time
          description: Client's current local time (YYYY-MM-DDTHH:mm:ssZD)
        - in: header
          name: X-SIGNATURE
          required: true
          schema:
            type: string
          description: HMAC_SHA512 signature of the request
        - in: header
          name: X-PARTNER-ID
          required: true
          schema:
            type: string
          description: Client ID generated by DOKU
        - in: header
          name: X-EXTERNAL-ID
          required: true
          schema:
            type: string
          description: Unique reference number for the day (Request ID)
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum: [application/json]
          description: Media type of the request body
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DebitStatusRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebitStatusResponse"

components:
  schemas:
    Amount:
      type: object
      required:
        - value
        - currency
      properties:
        value:
          type: string
          format: decimal
          description: Amount with 2 decimal places
        currency:
          type: string
          enum: [IDR]

    DebitStatusRequest:
      type: object
      required:
        - serviceCode
      properties:
        originalPartnerReferenceNo:
          type: string
          description: Original transaction identifier on service consumer system
        originalReferenceNo:
          type: string
          description: Original transaction identifier on service provider system
        originalExternalId:
          type: string
          description: Original External-ID on header message
        serviceCode:
          type: string
          enum: ["55"]
          description: API type indicator (55 for Check Status API)
        transactionDate:
          type: string
          format: date-time
          description: Transaction date (ISO 8601)
        amount:
          $ref: "#/components/schemas/Amount"
        merchantId:
          type: string
          description: Unique merchant identifier
        subMerchantId:
          type: string
          description: Sub merchant ID
        externalStoreId:
          type: string
          description: External Store ID for merchant
        additionalInfo:
          type: object
          properties:
            deviceId:
              type: string
            channel:
              type: string

    RefundHistory:
      type: object
      properties:
        refundNo:
          type: string
          description: Transaction Identifier on Service Provider System
        partnerReferenceNo:
          type: string
          description: ReferenceNumber from PJP AIS for the refund
        refundAmount:
          $ref: "#/components/schemas/Amount"
        refundStatus:
          type: string
          enum: ["00", "03", "04"]
          description: |
            00 = Success
            03 = Pending
            04 = Failed
        refundDate:
          type: string
          format: date-time
          description: Transaction date (ISO 8601)
        reason:
          type: string
          description: Refund reason

    DebitStatusResponse:
      type: object
      required:
        - responseCode
        - responseMessage
        - serviceCode
        - latestTransactionStatus
        - additionalInfo
      properties:
        responseCode:
          type: string
          maxLength: 7
          description: Response Code
        responseMessage:
          type: string
          maxLength: 150
          description: Response Description
        originalPartnerReferenceNo:
          type: string
          description: Original transaction identifier on service consumer system
        originalReferenceNo:
          type: string
          description: Original transaction identifier on service provider system
        approvalCode:
          type: string
          description: Unique number
        originalExternalId:
          type: string
          description: Original External-ID on header message
        serviceCode:
          type: string
          description: Transaction type indicator
        latestTransactionStatus:
          type: string
          enum: ["00", "01", "02", "03", "04", "05", "06", "07"]
          description: |
            00 = Success
            01 = Initiated
            02 = Paying
            03 = Pending
            04 = Refunded
            05 = Canceled
            06 = Failed
            07 = Not Found
        transactionStatusDesc:
          type: string
          description: Description status transaction
        originalResponseCode:
          type: string
          description: Response code
        originalResponseMessage:
          type: string
          description: Response description
        sessionId:
          type: string
          description: Transaction invoice ID
        requestID:
          type: string
          description: Transaction request ID
        refundHistory:
          type: array
          items:
            $ref: "#/components/schemas/RefundHistory"
        transAmount:
          $ref: "#/components/schemas/Amount"
        feeAmount:
          $ref: "#/components/schemas/Amount"
        paidTime:
          type: string
          format: date-time
          description: Transaction date (ISO 8601)
        additionalInfo:
          type: object
          properties:
            deviceId:
              type: string
            channel:
              type: string
