openapi: 3.0.0
info:
  title: SNAP API Virtual Account
  description: Backend Integration to check status API
  version: "1.0"
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://{api-domain}

paths:
  /orders/v1.0/transfer-va/status:
    post:
      summary: Check Virtual Account Status
      description: Get the status and details of a virtual account transaction
      operationId: checkVAStatus
      tags:
        - Backend Integration to check status Virtual Account
      parameters:
        - in: header
          name: X-TIMESTAMP
          required: true
          schema:
            type: string
            format: date-time
          description: Client's current local time (YYYY-MM-DDTHH:mm:ssZD)
        - in: header
          name: X-SIGNATURE
          required: true
          schema:
            type: string
          description: HMAC_SHA512 signature of the request
        - in: header
          name: X-PARTNER-ID
          required: true
          schema:
            type: string
          description: Client ID generated by DOKU
        - in: header
          name: X-EXTERNAL-ID
          required: true
          schema:
            type: string
          description: Unique reference number for the day (Request ID)
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum: [application/json]
          description: Media type of the request body
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VAStatusRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VAStatusResponse"

components:
  schemas:
    VAStatusRequest:
      type: object
      required:
        - partnerServiceId
        - customerNo
        - virtualAccountNo
      properties:
        partnerServiceId:
          type: string
          maxLength: 8
          description: Derivative of X-PARTNER-ID, similar to company code, 8 digit left padding space
        customerNo:
          type: string
          maxLength: 20
          description: Unique customer number
        virtualAccountNo:
          type: string
          maxLength: 28
          description: Combination of partnerServiceId and customerNo
        inquiryRequestId:
          type: string
          maxLength: 128
          description: Unique identifier from Inquiry
        paymentRequestId:
          type: string
          maxLength: 128
          description: Customer address
        additionalInfo:
          type: object
          description: Additional information

    VAStatusResponse:
      type: object
      required:
        - responseCode
        - responseMessage
        - virtualAccountData
        - additionalInfo
      properties:
        responseCode:
          type: string
          maxLength: 7
          description: Response code
        responseMessage:
          type: string
          maxLength: 150
          description: Response description
        virtualAccountData:
          type: object
          required:
            - partnerServiceId
            - customerNo
            - virtualAccountNo
            - paidAmount
            - billDetails
          properties:
            paymentFlagReason:
              description: Reason for Payment Status multi language
              type: object
              properties:
                english:
                  type: string
                indonesia:
                  type: string
            partnerServiceId:
              type: string
              description: Derivative of X-PARTNER-ID
            customerNo:
              type: string
              description: Unique number
            virtualAccountNo:
              type: string
              description: Combined partnerServiceId and customerNo
            inquiryRequestId:
              type: string
              description: Unique identifier from Inquiry
            paymentRequestId:
              type: string
              description: Unique identifier for this Payment from PJP. Mandatory if Payment happened.
            paidAmount:
              type: object
              required:
                - value
                - currency
              properties:
                value:
                  type: string
                  format: decimal
                  description: Amount with 2 decimal places
                currency:
                  type: string
                  enum: [IDR]
            billDetails:
              type: array
              items:
                type: object
                properties:
                  billAmount:
                    type: object
                    required:
                      - value
                      - currency
                    properties:
                      value:
                        type: string
                        format: decimal
                      currency:
                        type: string
                        enum: [IDR]
        additionalInfo:
          type: object
          required:
            - acquirer
          properties:
            acquirer:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  enum: [BRI, BNI, BNC, BTN, DANAMON, MANDIRI, PERMATA]
            trxId:
              type: string
